# Generated by Django 5.2.3 on 2025-06-28 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Provinsi',
            },
        ),
        migrations.CreateModel(
            name='AlatMusik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('asal_daerah', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alat_musik', to='alatmusik_app.provinsi')),
            ],
            options={
                'verbose_name_plural': 'Alat Musik',
            },
        ),
    ]
